### ISSUE TITLE
Websocket Errors : notAnUpgrade(401) and "masked and rsv data is not currently supported"

### ISSUE THREAD

**Issue by spiresweet** [deepgram-devs/deepgram-live-transcripts-ios#1]
Hello,

I just downloaded your example code, registered and created a new API_KEY.  The Websocket library you are using (Starscream), when connecting, is throwing two errors back to back.

notAnUpgrade(401)
and
▿ Optional<Error>
  ▿ some : WSError
    - type : Starscream.ErrorType.protocolError
    - message : "masked and rsv data is not currently supported"
    - code : 1002

Here is the default socket variable being utilized

    private lazy var socket: WebSocket = {
        let url = URL(string: "wss://api.deepgram.com/v1/listen?encoding=linear16&sample_rate=48000&channels=1")!
        var urlRequest = URLRequest(url: url)
        urlRequest.setValue(apiKey, forHTTPHeaderField: "Authorization")
        return WebSocket(request: urlRequest)
    }()

Audio data is coming in from the app from the AudioEngine via the block

        converterNode.installTap(onBus: 0, bufferSize: 1024, format: converterNode.outputFormat(forBus: 0)) { (buffer: AVAudioPCMBuffer!, time: AVAudioTime!) -> Void in
            if let data = self.toNSData(buffer: buffer) {
                self.socket.write(data: data)
            }
        }

If there is more information I can provide to help please let me know. Thanks

**Comment by spiresweet** [comment]
Found cause of issue. I was not placing "Token....." in front of my ApiKey

    private let apiKey = "........."
    private var token = ""
    private let audioEngine = AVAudioEngine()
    var webSocketConnected : Bool = false
    
    private lazy var socket: WebSocket = {
        token = "Token \(apiKey)"
        let url = URL(string: "wss://api.deepgram.com/v1/listen")!
        var urlRequest = URLRequest(url: url)
        urlRequest.setValue(token, forHTTPHeaderField: "Authorization")
        return WebSocket(request: urlRequest, certPinner: FoundationSecurity(allowSelfSigned: true))
    }()

**Comment by blueberrychopsticks** [comment]
Great fix @spiresweet. I'd been running into the same issue and this fixed it for me as well. Very excited to get to start using Deepgram on iOS now, thank you!

I'm curious - did you just arrive at this answer by tinkering or where did you find how this fixes the issue?
